void PutSurface();

void freeBitmapData();
void _CameraDeviceGetPreviewSurface();
void CapturePreviewSurface();
void CameraDeviceDeallocate();
void CameraDeviceRegisterClass();
void CameraDeviceGetTypeID();
void CameraDeviceSetProperties();
void CameraDeviceStopPreview();
void CameraDeviceSetClient();
void CameraDeviceSetCaptureCallback();
void CameraDeviceSetImageQueueHelper();
void CameraDeviceScheduleWithRunLoop(char * a, CFRunLoopRef rl);
void CameraDeviceUnscheduleFromRunLoop();
char * CameraDeviceCreate();
void CameraDeviceGetPropertiesCopy();
void CameraDeviceTakePhoto();
void CreateBGRABuffer();
void CameraDeviceStartPreview();
void CameraDeviceRecycleSurface();
void CameraDeviceCaptureCallback();        
void CameraImageQueueHelperDeallocate();   
void CameraImageQueueHelperRegisterClass();
void CameraImageQueueHelperGetTypeID();    
void CameraImageQueueHelperGetQueue();     
void CameraImageQueueHelperReleaseBuffer();
void CameraImageQueueHelperHandleCallback();
void CameraImageQueueHelperCreate();       
void openJPEGDriverUserClientConnection(); 
void closeJPEGDriverUserClientConnection();
void encodeJPEGWithDriver();
void JPEGCompressSurface();