/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <UIKit/UIEvent.h>

@class NSTimer;

@interface UIMotionEvent : UIEvent
{
    id _motionAccelerometer;
    int _subtype;
    int _shakeState;
    int _stateMachineState;
    double _shakeStartTime;
    double _lastMovementTime;
    double _highLevelTime;
    double _lowEndTimeout;
    NSTimer *_idleTimer;
    BOOL _sentMotionBegan;
    float _lowPassState[10];
    unsigned int _lowPassStateIndex;
    unsigned int _highPassStateIndex;
    float _highPassState[2];
}

- (id)_init;
- (void)dealloc;
- (int)type;
- (int)subtype;
- (void)_setSubtype:(int)arg1;
- (id)description;
- (void)_willResume;
- (void)_willSuspend;
- (void)_accelerometerDidDetectMovementWithTimestamp:(double)arg1;
- (void)_idleTimerFired;
- (void)accelerometer:(id)arg1 didAccelerateWithTimeStamp:(double)arg2 x:(float)arg3 y:(float)arg4 z:(float)arg5 eventType:(int)arg6;
- (int)_feedStateMachine:(float)arg1 currentState:(int)arg2 timestamp:(double)arg3;
- (float)_highPass:(float)arg1;
- (void)_resetLowPassState;
- (float)_lowPass:(float)arg1;
- (float)_determineShakeLevelX:(float)arg1 y:(float)arg2 currentState:(int)arg3;
- (int)_shakeState;
@property(nonatomic) int shakeState; // @synthesize shakeState=_shakeState;

@end

